import { ENVIRONMENT_VARIABLES, pickAndGenerateSchema } from '../';

export type BackendConfig = {
    POSTGRES_DATABASE_NAME: string;
    POSTGRES_DATABASE_HOST: string;
    POSTGRES_PASSWORD: string;
    POSTGRES_PORT: number;
    POSTGRES_USER: string;
    BACKEND_PORT: number;
    BACKEND_URL: string;
    NODE_ENV: string;
    ENVIRONMENT: string;
};

export const backendConfigSchema = pickAndGenerateSchema([
    ENVIRONMENT_VARIABLES.POSTGRES_DATABASE_NAME,
    ENVIRONMENT_VARIABLES.POSTGRES_DATABASE_HOST,
    ENVIRONMENT_VARIABLES.POSTGRES_PASSWORD,
    ENVIRONMENT_VARIABLES.POSTGRES_PORT,
    ENVIRONMENT_VARIABLES.POSTGRES_USER,
    ENVIRONMENT_VARIABLES.BACKEND_PORT,
    ENVIRONMENT_VARIABLES.BACKEND_URL,
    ENVIRONMENT_VARIABLES.NODE_ENV,
    ENVIRONMENT_VARIABLES.ENVIRONMENT,
]);
